services:
  app:
    image: ${APP_IMAGE}
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=app
      - DB_PASS=app
    depends_on:
      - db
    networks:
      - edge
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.pr-${PR_NUMBER}.rule=Host(`pr-${PR_NUMBER}.localhost`)
      - traefik.http.routers.pr-${PR_NUMBER}.entrypoints=web
      - traefik.http.services.pr-${PR_NUMBER}.loadbalancer.server.port=80

  db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    image: pr-mysql:${PR_NUMBER:-local}
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal

  adminer:
    image: adminer:4
    depends_on:
      - db
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - edge
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.pr-${PR_NUMBER}-db.rule=Host(`pr-${PR_NUMBER}-db.localhost`)
      - traefik.http.routers.pr-${PR_NUMBER}-db.entrypoints=web
      - traefik.http.services.pr-${PR_NUMBER}-db.loadbalancer.server.port=8080

volumes:
  db_data:

networks:
  edge:
    external: true
  internal:
    driver: bridge
